In [1]:
import math
import sklearn
import numpy as np , pandas as pd
import seaborn as sb
from sklearn import tree
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
import sklearn
from pandas import Series , DataFrame
from pylab import rcParams
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import classification_report
import re
import datetime
from dateutil.relativedelta import relativedelta
from datetime import date
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

In [2]:
datafile_train=r'C:\Users\Mr. Jarvis\Desktop\python project\project 1\Consumer_Complaints_train.csv'

In [3]:
datafile_train

'C:\\Users\\Mr. Jarvis\\Desktop\\python project\\project 1\\Consumer_Complaints_train.csv'

In [4]:
datafile_test=r'C:\Users\Mr. Jarvis\Desktop\python project\project 1\Consumer_Complaints_test_share.csv'

In [5]:
datafile_test

'C:\\Users\\Mr. Jarvis\\Desktop\\python project\\project 1\\Consumer_Complaints_test_share.csv'

In [6]:
cc_train = pd.read_csv(datafile_train)

In [7]:
cc_train

Date received                  Product                  Sub-product  \
0         2014-05-15              Credit card                          NaN   
1         2014-09-18  Bank account or service  (CD) Certificate of deposit   
2         2014-03-13         Credit reporting                          NaN   
3         2015-07-17              Credit card                          NaN   
4         2014-11-20              Credit card                          NaN   
...              ...                      ...                          ...   
478416    2015-06-30  Bank account or service             Checking account   
478417    2013-06-20              Credit card                          NaN   
478418    2014-09-09         Credit reporting                          NaN   
478419    2012-09-21                 Mortgage  Conventional fixed mortgage   
478420    2014-10-30            Consumer Loan                Vehicle lease   

                                           Issue                Sub-issue  \
0                              Billing statement                      NaN   
1       Making/receiving payments, sending money                      NaN   
2         Incorrect information on credit report           Account status   
3                              Billing statement                      NaN   
4                              Transaction issue                      NaN   
...                                          ...                      ...   
478416     Problems caused by my funds being low                      NaN   
478417                      Collection practices                      NaN   
478418    Incorrect information on credit report  Information is not mine   
478419  Loan modification,collection,foreclosure                      NaN   
478420                Managing the loan or lease                      NaN   

                             Consumer complaint narrative  \
0                                                     NaN   
1                                                     NaN   
2                                                     NaN   
3       My credit card statement from US Bank, XXXX. X...   
4                                                     NaN   
...                                                   ...   
478416                                                NaN   
478417                                                NaN   
478418                                                NaN   
478419                                                NaN   
478420                                                NaN   

                                 Company public response  \
0                                                    NaN   
1                                                    NaN   
2                                                    NaN   
3       Company chooses not to provide a public response   
4                                                    NaN   
...                                                  ...   
478416                                               NaN   
478417                                               NaN   
478418                                               NaN   
478419                                               NaN   
478420                                               NaN   

                                Company State ZIP code            Tags  \
0                 Wells Fargo & Company    MI    48342  Older American   
1                     Santander Bank US    PA    18042             NaN   
2                               Equifax    CA    92427             NaN   
3                          U.S. Bancorp    GA    305XX  Older American   
4                       Bank of America    MA    02127             NaN   
...                                 ...   ...      ...             ...   
478416             JPMorgan Chase & Co.    TX    77008             NaN   
478417                         Citibank    AL    36111             NaN   
478418                   

In [8]:
cc_test = pd.read_csv(datafile_test)

In [9]:
cc_test

Date received                  Product  \
0         2014-01-18  Bank account or service   
1         2016-03-31          Debt collection   
2         2012-03-08                 Mortgage   
3         2016-01-07         Credit reporting   
4         2013-08-23                 Mortgage   
...              ...                      ...   
119601    2012-09-15              Credit card   
119602    2016-07-21         Credit reporting   
119603    2015-06-09          Debt collection   
119604    2014-02-26          Debt collection   
119605    2015-02-11          Debt collection   

                                   Sub-product  \
0           Cashing a check without an account   
1                                  Credit card   
2       Conventional adjustable mortgage (ARM)   
3                                          NaN   
4                                 FHA mortgage   
...                                        ...   
119601                                     NaN   
119602                                     NaN   
119603   Other (i.e. phone, health club, etc.)   
119604                             Credit card   
119605   Other (i.e. phone, health club, etc.)   

                                           Issue  \
0                       Deposits and withdrawals   
1          Cont'd attempts collect debt not owed   
2       Loan servicing, payments, escrow account   
3       Unable to get credit report/credit score   
4       Loan modification,collection,foreclosure   
...                                          ...   
119601                Closing/Cancelling account   
119602  Credit reporting company's investigation   
119603           Disclosure verification of debt   
119604           Disclosure verification of debt   
119605     Cont'd attempts collect debt not owed   

                                       Sub-issue  \
0                                            NaN   
1                                  Debt was paid   
2                                            NaN   
3         Problem getting report or credit score   
4                                            NaN   
...                                          ...   
119601                                       NaN   
119602  No notice of investigation status/result   
119603      Not given enough info to verify debt   
119604      Not given enough info to verify debt   
119605                          Debt is not mine   

                             Consumer complaint narrative  \
0                                                     NaN   
1                                                     NaN   
2                                                     NaN   
3                                                     NaN   
4                                                     NaN   
...                                                   ...   
119601                                                NaN   
119602  On XXXX/XXXX/16 a dispute and validation of a ...   
119603                                                NaN   
119604                                                NaN   
119605                                                NaN   

                                  Company public response  \
0                                                     NaN   
1                                                     NaN   
2                                                     NaN   
3        Company chooses not to provide a public response   
4                                                     NaN   
...                                                   ...   
119601                                                NaN   
119602  Company has responded to the consumer and the ...   
119603   Company chooses not to provide a public response   
119604                                                NaN   
119605                                                NaN   

                                       Company State ZIP code            Tags  \
0                   

In [10]:
cc_train.dtypes

Date received                   object
Product                         object
Sub-product                     object
Issue                           object
Sub-issue                       object
Consumer complaint narrative    object
Company public response         object
Company                         object
State                           object
ZIP code                        object
Tags                            object
Consumer consent provided?      object
Submitted via                   object
Date sent to company            object
Company response to consumer    object
Timely response?                object
Consumer disputed?              object
Complaint ID                     int64
dtype: object

In [11]:
cc_test.dtypes

Date received                   object
Product                         object
Sub-product                     object
Issue                           object
Sub-issue                       object
Consumer complaint narrative    object
Company public response         object
Company                         object
State                           object
ZIP code                        object
Tags                            object
Consumer consent provided?      object
Submitted via                   object
Date sent to company            object
Company response to consumer    object
Timely response?                object
Complaint ID                     int64
dtype: object

In [12]:
cc_train.shape

(478421, 18)

In [13]:
cc_test.shape

(119606, 17)

In [14]:
cc_train.isnull().sum()

Date received                        0
Product                              0
Sub-product                     138473
Issue                                0
Sub-issue                       292625
Consumer complaint narrative    403327
Company public response         388029
Company                              0
State                             3839
ZIP code                          3848
Tags                            411215
Consumer consent provided?      342934
Submitted via                        0
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Consumer disputed?                   0
Complaint ID                         0
dtype: int64

In [15]:
cc_test.isnull().sum()

Date received                        0
Product                              0
Sub-product                      34752
Issue                                0
Sub-issue                        73060
Consumer complaint narrative    101049
Company public response          96830
Company                              0
State                              925
ZIP code                           926
Tags                            102735
Consumer consent provided?       85742
Submitted via                        1
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Complaint ID                         0
dtype: int64

In [16]:
cc_test["Consumer disputed?"] = np.nan

In [17]:
cc_train["data"] = "train"

In [18]:
cc_test["data"] = "test"

In [19]:
cc_train.shape

(478421, 19)

In [20]:
cc_test.shape

(119606, 19)

In [21]:
cc_train.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID', 'data'],
      dtype='object')

In [22]:
cc_test.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Complaint ID', 'Consumer disputed?', 'data'],
      dtype='object')

In [23]:
cc_test = cc_test[cc_train.columns]

In [24]:
cc_full = pd.concat([cc_train , cc_test],axis=0)

In [25]:
cc_full

Date received                  Product  \
0         2014-05-15              Credit card   
1         2014-09-18  Bank account or service   
2         2014-03-13         Credit reporting   
3         2015-07-17              Credit card   
4         2014-11-20              Credit card   
...              ...                      ...   
119601    2012-09-15              Credit card   
119602    2016-07-21         Credit reporting   
119603    2015-06-09          Debt collection   
119604    2014-02-26          Debt collection   
119605    2015-02-11          Debt collection   

                                  Sub-product  \
0                                         NaN   
1                 (CD) Certificate of deposit   
2                                         NaN   
3                                         NaN   
4                                         NaN   
...                                       ...   
119601                                    NaN   
119602                                    NaN   
119603  Other (i.e. phone, health club, etc.)   
119604                            Credit card   
119605  Other (i.e. phone, health club, etc.)   

                                           Issue  \
0                              Billing statement   
1       Making/receiving payments, sending money   
2         Incorrect information on credit report   
3                              Billing statement   
4                              Transaction issue   
...                                          ...   
119601                Closing/Cancelling account   
119602  Credit reporting company's investigation   
119603           Disclosure verification of debt   
119604           Disclosure verification of debt   
119605     Cont'd attempts collect debt not owed   

                                       Sub-issue  \
0                                            NaN   
1                                            NaN   
2                                 Account status   
3                                            NaN   
4                                            NaN   
...                                          ...   
119601                                       NaN   
119602  No notice of investigation status/result   
119603      Not given enough info to verify debt   
119604      Not given enough info to verify debt   
119605                          Debt is not mine   

                             Consumer complaint narrative  \
0                                                     NaN   
1                                                     NaN   
2                                                     NaN   
3       My credit card statement from US Bank, XXXX. X...   
4                                                     NaN   
...                                                   ...   
119601                                                NaN   
119602  On XXXX/XXXX/16 a dispute and validation of a ...   
119603                                                NaN   
119604                                                NaN   
119605                                                NaN   

                                  Company public response  \
0                                                     NaN   
1                                                     NaN   
2                                                     NaN   
3        Company chooses not to provide a public response   
4                                                     NaN   
...                                                   ...   
119601                                                NaN   
119602  Company has responded to the consumer and the ...   
119603   Company chooses not to provide a public response   
119604                                                NaN   
119605                                                NaN   

                                     Company State ZIP code            Tags  \
0                      Wells Fargo

In [26]:
cc_full.shape

(598027, 19)

In [27]:
cc_full.isnull().sum()

Date received                        0
Product                              0
Sub-product                     173225
Issue                                0
Sub-issue                       365685
Consumer complaint narrative    504376
Company public response         484859
Company                              0
State                             4764
ZIP code                          4774
Tags                            513950
Consumer consent provided?      428676
Submitted via                        1
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Consumer disputed?              119606
Complaint ID                         0
data                                 0
dtype: int64

In [28]:
unused_cols = cc_full.isnull().sum()[cc_full.isnull().sum()>(0.5*cc_full.shape[0])].keys()

In [29]:
unused_cols

Index(['Sub-issue', 'Consumer complaint narrative', 'Company public response',
       'Tags', 'Consumer consent provided?'],
      dtype='object')

In [30]:
cc_full.drop(columns=unused_cols,axis=1,inplace=True)

In [31]:
cc_full.shape

(598027, 14)

In [32]:
cc_full.drop(columns=["Complaint ID"],inplace=True)

In [33]:
cc_full.shape

(598027, 13)

In [34]:
cc_full.isnull().sum()

Date received                        0
Product                              0
Sub-product                     173225
Issue                                0
Company                              0
State                             4764
ZIP code                          4774
Submitted via                        1
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Consumer disputed?              119606
data                                 0
dtype: int64

In [35]:
cc_full["Sub-product"] = np.where(cc_full["Sub-product"].isnull(),"not_available",cc_full["Sub-product"])

In [36]:
cc_full["Sub-product"].isnull().sum()

0

In [37]:
cc_full["State"] = np.where(cc_full["State"].isnull(),"not_available_state",cc_full["State"])

In [38]:
cc_full["State"].isnull().sum()

0

In [40]:
cc_full["ZIP code"] = np.where(cc_full["ZIP code"].isnull(),"not_available",cc_full["ZIP code"])

In [41]:
cc_full["ZIP code"].isnull().sum()

0

In [42]:
cc_full["Submitted via"].mode()

0    Web
dtype: object

In [43]:
cc_full["Submitted via"] = np.where(cc_full["Submitted via"].isnull() , cc_full["Submitted via"].mode()[0],cc_full["Submitted via"])

In [44]:
cc_full["Submitted via"].isnull().sum()

0

In [45]:
cc_full.isnull().sum()

Date received                        0
Product                              0
Sub-product                          0
Issue                                0
Company                              0
State                                0
ZIP code                             0
Submitted via                        0
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Consumer disputed?              119606
data                                 0
dtype: int64

In [46]:
cc_full["Date received"] = pd.to_datetime(cc_full["Date received"])

In [47]:
cc_full["Date sent to company"] = pd.to_datetime(cc_full["Date sent to company"])

In [48]:
cc_full.dtypes

Date received                   datetime64[ns]
Product                                 object
Sub-product                             object
Issue                                   object
Company                                 object
State                                   object
ZIP code                                object
Submitted via                           object
Date sent to company            datetime64[ns]
Company response to consumer            object
Timely response?                        object
Consumer disputed?                      object
data                                    object
dtype: object

In [49]:
cc_full["Day_Difference"] = (cc_full["Date sent to company"] - cc_full["Date received"] )/np.timedelta64(1,"D")

In [50]:
cc_full

Date received                  Product  \
0         2014-05-15              Credit card   
1         2014-09-18  Bank account or service   
2         2014-03-13         Credit reporting   
3         2015-07-17              Credit card   
4         2014-11-20              Credit card   
...              ...                      ...   
119601    2012-09-15              Credit card   
119602    2016-07-21         Credit reporting   
119603    2015-06-09          Debt collection   
119604    2014-02-26          Debt collection   
119605    2015-02-11          Debt collection   

                                  Sub-product  \
0                               not_available   
1                 (CD) Certificate of deposit   
2                               not_available   
3                               not_available   
4                               not_available   
...                                       ...   
119601                          not_available   
119602                          not_available   
119603  Other (i.e. phone, health club, etc.)   
119604                            Credit card   
119605  Other (i.e. phone, health club, etc.)   

                                           Issue  \
0                              Billing statement   
1       Making/receiving payments, sending money   
2         Incorrect information on credit report   
3                              Billing statement   
4                              Transaction issue   
...                                          ...   
119601                Closing/Cancelling account   
119602  Credit reporting company's investigation   
119603           Disclosure verification of debt   
119604           Disclosure verification of debt   
119605     Cont'd attempts collect debt not owed   

                                     Company State ZIP code Submitted via  \
0                      Wells Fargo & Company    MI    48342           Web   
1                          Santander Bank US    PA    18042      Referral   
2                                    Equifax    CA    92427      Referral   
3                               U.S. Bancorp    GA    305XX           Web   
4                            Bank of America    MA    02127           Web   
...                                      ...   ...      ...           ...   
119601                  JPMorgan Chase & Co.    IL    60538           Web   
119602                              Experian    CA    956XX           Web   
119603  FAIR COLLECTIONS & OUTSOURCING, INC.    CA    90803         Phone   
119604                  Encore Capital Group    PA    17764         Phone   
119605    AllianceOne Recievables Management    CA    92103           Web   

       Date sent to company     Company response to consumer Timely response?  \
0                2014-05-16          Closed with explanation              Yes   
1                2014-09-24                           Closed              Yes   
2                2014-04-03  Closed with non-monetary relief              Yes   
3                2015-07-17      Closed with monetary relief              Yes   
4                2014-11-28          Closed with explanation              Yes   
...                     ...                              ...              ...   
119601           2012-09-21      Closed with monetary relief              Yes   
119602           2016-07-21          Closed with explanation              Yes   
119603           2015-06-12          Closed with explanation              Yes   
119604           2014-02-27          Closed with explanation              Yes   
119605           2015-02-11          Closed with explanation              Yes   

       Consumer disputed?   data  Day_Difference  
0                      No  train             1.0  
1                      No  train             6.0  
2                      No  train            21.0  
3                      No  train             0.0  
4                      No  train             8.0  


In [51]:
cc_full.drop(columns =["Date received","Date sent to company"], inplace = True)

In [52]:
cc_full.shape

(598027, 12)

In [53]:
cc_full

Product                            Sub-product  \
0                   Credit card                          not_available   
1       Bank account or service            (CD) Certificate of deposit   
2              Credit reporting                          not_available   
3                   Credit card                          not_available   
4                   Credit card                          not_available   
...                         ...                                    ...   
119601              Credit card                          not_available   
119602         Credit reporting                          not_available   
119603          Debt collection  Other (i.e. phone, health club, etc.)   
119604          Debt collection                            Credit card   
119605          Debt collection  Other (i.e. phone, health club, etc.)   

                                           Issue  \
0                              Billing statement   
1       Making/receiving payments, sending money   
2         Incorrect information on credit report   
3                              Billing statement   
4                              Transaction issue   
...                                          ...   
119601                Closing/Cancelling account   
119602  Credit reporting company's investigation   
119603           Disclosure verification of debt   
119604           Disclosure verification of debt   
119605     Cont'd attempts collect debt not owed   

                                     Company State ZIP code Submitted via  \
0                      Wells Fargo & Company    MI    48342           Web   
1                          Santander Bank US    PA    18042      Referral   
2                                    Equifax    CA    92427      Referral   
3                               U.S. Bancorp    GA    305XX           Web   
4                            Bank of America    MA    02127           Web   
...                                      ...   ...      ...           ...   
119601                  JPMorgan Chase & Co.    IL    60538           Web   
119602                              Experian    CA    956XX           Web   
119603  FAIR COLLECTIONS & OUTSOURCING, INC.    CA    90803         Phone   
119604                  Encore Capital Group    PA    17764         Phone   
119605    AllianceOne Recievables Management    CA    92103           Web   

           Company response to consumer Timely response? Consumer disputed?  \
0               Closed with explanation              Yes                 No   
1                                Closed              Yes                 No   
2       Closed with non-monetary relief              Yes                 No   
3           Closed with monetary relief              Yes                 No   
4               Closed with explanation              Yes                 No   
...                                 ...              ...                ...   
119601      Closed with monetary relief              Yes                NaN   
119602          Closed with explanation              Yes                NaN   
119603          Closed with explanation              Yes                NaN   
119604          Closed with explanation              Yes                NaN   
119605          Closed with explanation              Yes                NaN   

         data  Day_Difference  
0       train             1.0  
1       train             6.0  
2       train            21.0  
3       train             0.0  
4       train             8.0  
...       ...             ...  
119601   test             6.0  
119602   test             0.0  
119603   test             3.0  
119604   test             1.0  
119605   test             0.0  

[598027 rows x 12 columns]

In [54]:
def dummies(data,var,freq_cutoff=0):
    t= data[var].value_counts(normalize=True) 
    t=t[t.values>freq_cutoff] 
    t=t.sort_values() 
    t_min=t.idxmin()
    t=t.drop([t_min])
    categories=t.index

    for cat in categories :
        name=var+'_'+cat
        name=re.sub(" ","",name) 
        name=re.sub("-","_",name)
        name=re.sub("\\?","Q",name) 
        name=re.sub("<","LT_",name)
        name=re.sub("\\+","",name) 
        name=re.sub("\\/","_",name) 
        name=re.sub(">","GT_",name) 
        name=re.sub("=","EQ_",name)
        name=re.sub(",","",name)
        data[name]=(data[var]==cat)+0 
               
    data=data.drop(columns=[var])
    return data

In [55]:
cc_full.dtypes

Product                          object
Sub-product                      object
Issue                            object
Company                          object
State                            object
ZIP code                         object
Submitted via                    object
Company response to consumer     object
Timely response?                 object
Consumer disputed?               object
data                             object
Day_Difference                  float64
dtype: object

In [56]:
import re

In [57]:
cc_full = dummies(cc_full ,"Product",0.05)

In [58]:
cc_full = dummies(cc_full ,"Sub-product",0.05)

In [59]:
cc_full = dummies(cc_full ,"Issue",0.05)

In [60]:
cc_full = dummies(cc_full , "Company",0.05)

In [61]:
cc_full = dummies(cc_full , "State" ,0.05)

In [62]:
cc_full = dummies(cc_full ,"Submitted via" ,0.05)

In [63]:
cc_full = dummies(cc_full ,"Company response to consumer" ,0.05)

In [64]:
cc_full = dummies(cc_full , "Timely response?")

In [67]:
cc_full["ZIP code"].isnull().sum()

0

In [68]:
cc_full.head()

ZIP code Consumer disputed?   data  Day_Difference  Product_Creditcard  \
0    48342                 No  train             1.0                   1   
1    18042                 No  train             6.0                   0   
2    92427                 No  train            21.0                   0   
3    305XX                 No  train             0.0                   1   
4    02127                 No  train             8.0                   1   

   Product_Creditreporting  Product_Debtcollection  Product_Mortgage  \
0                        0                       0                 0   
1                        0                       0                 0   
2                        1                       0                 0   
3                        0                       0                 0   
4                        0                       0                 0   

   Sub_product_Checkingaccount  Sub_product_Conventionalfixedmortgage  ...  \
0                            0                                      0  ...   
1                            0                                      0  ...   
2                            0                                      0  ...   
3                            0                                      0  ...   
4                            0                                      0  ...   

   Company_BankofAmerica  State_TX  State_FL  State_CA  Submittedvia_Phone  \
0                      0         0         0         0                   0   
1                      0         0         0         0                   0   
2                      0         0         0         1                   0   
3                      0         0         0         0                   0   
4                      1         0         0         0                   0   

   Submittedvia_Referral  Submittedvia_Web  \
0                      0                 1   
1                      1                 0   
2                      1                 0   
3                      0                 1   
4                      0                 1   

   Companyresponsetoconsumer_Closedwithnon_monetaryrelief  \
0                                                  0        
1                                                  0        
2                                                  1        
3                                                  0        
4                                                  0        

   Companyresponsetoconsumer_Closedwithexplanation  TimelyresponseQ_Yes  
0                                                1                    1  
1                                                0                    1  
2                                                0                    1  
3                                                0                    1  
4                                                1                    1  

[5 rows x 28 columns]

In [69]:
cc_full.drop(columns=["ZIP code"] , axis=1 , inplace=True)

In [70]:
cc_full.shape

(598027, 27)

In [73]:
cc_full["Consumer disputed?"].value_counts()

No     376990
Yes    101431
Name: Consumer disputed?, dtype: int64

In [74]:
cc_full.dtypes

Consumer disputed?                                         object
data                                                       object
Day_Difference                                            float64
Product_Creditcard                                          int32
Product_Creditreporting                                     int32
Product_Debtcollection                                      int32
Product_Mortgage                                            int32
Sub_product_Checkingaccount                                 int32
Sub_product_Conventionalfixedmortgage                       int32
Sub_product_Othermortgage                                   int32
Sub_product_not_available                                   int32
Issue_Loanservicingpaymentsescrowaccount                    int32
Issue_Incorrectinformationoncreditreport                    int32
Issue_Loanmodificationcollectionforeclosure                 int32
Company_Equifax                                             int32
Company_JP

In [75]:
cc_train = cc_full[cc_full['data']=='train']

In [76]:
del cc_train['data'] 

In [77]:
cc_test = cc_full[cc_full['data']=='test']

In [78]:
cc_test.drop(['Consumer disputed?','data'] , axis=1 , inplace=True)

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [79]:
train1 , train2 = train_test_split(cc_train , test_size = 0.25 , random_state=2)

x_train1 = train1.drop(["Consumer disputed?"],1)
y_train1 = train1["Consumer disputed?"]

In [80]:
x_train2 = train2.drop(["Consumer disputed?"],1)
y_train2 = train2["Consumer disputed?"]

In [81]:
x_train1.reset_index(drop=True,inplace=True)
y_train1.reset_index(drop=True,inplace=True)

In [82]:
model = LogisticRegression(fit_intercept=True)

In [89]:
params = {'class_weight':['balanced'],
        'n_jobs':[-1],
'penalty':['l1','l2'],
'C':np.linspace(1,1000,10)}

In [90]:
params

{'class_weight': ['balanced'],
 'n_jobs': [-1],
 'penalty': ['l1', 'l2'],
 'C': array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.])}

In [91]:
grid_search = GridSearchCV(model,param_grid=params,cv=5,scoring="roc_auc")

In [92]:
x_train1.shape

(358815, 25)

In [93]:
y_train1.shape

(358815,)

In [94]:
x_train2.shape

(119606, 25)

In [95]:
y_train2.shape

(119606,)

In [96]:
cc_train.shape

(478421, 26)

In [97]:
cc_test.shape

(119606, 25)

In [101]:
train1.shape

(358815, 26)

In [102]:
train2.shape

(119606, 26)

In [103]:
358815+119606

478421

In [99]:
cc_full.columns

Index(['Consumer disputed?', 'data', 'Day_Difference', 'Product_Creditcard',
       'Product_Creditreporting', 'Product_Debtcollection', 'Product_Mortgage',
       'Sub_product_Checkingaccount', 'Sub_product_Conventionalfixedmortgage',
       'Sub_product_Othermortgage', 'Sub_product_not_available',
       'Issue_Loanservicingpaymentsescrowaccount',
       'Issue_Incorrectinformationoncreditreport',
       'Issue_Loanmodificationcollectionforeclosure', 'Company_Equifax',
       'Company_JPMorganChase&Co.', 'Company_WellsFargo&Company',
       'Company_BankofAmerica', 'State_TX', 'State_FL', 'State_CA',
       'Submittedvia_Phone', 'Submittedvia_Referral', 'Submittedvia_Web',
       'Companyresponsetoconsumer_Closedwithnon_monetaryrelief',
       'Companyresponsetoconsumer_Closedwithexplanation',
       'TimelyresponseQ_Yes'],
      dtype='object')

In [98]:
cc_train.columns

Index(['Consumer disputed?', 'Day_Difference', 'Product_Creditcard',
       'Product_Creditreporting', 'Product_Debtcollection', 'Product_Mortgage',
       'Sub_product_Checkingaccount', 'Sub_product_Conventionalfixedmortgage',
       'Sub_product_Othermortgage', 'Sub_product_not_available',
       'Issue_Loanservicingpaymentsescrowaccount',
       'Issue_Incorrectinformationoncreditreport',
       'Issue_Loanmodificationcollectionforeclosure', 'Company_Equifax',
       'Company_JPMorganChase&Co.', 'Company_WellsFargo&Company',
       'Company_BankofAmerica', 'State_TX', 'State_FL', 'State_CA',
       'Submittedvia_Phone', 'Submittedvia_Referral', 'Submittedvia_Web',
       'Companyresponsetoconsumer_Closedwithnon_monetaryrelief',
       'Companyresponsetoconsumer_Closedwithexplanation',
       'TimelyresponseQ_Yes'],
      dtype='object')

In [100]:
cc_test.columns

Index(['Day_Difference', 'Product_Creditcard', 'Product_Creditreporting',
       'Product_Debtcollection', 'Product_Mortgage',
       'Sub_product_Checkingaccount', 'Sub_product_Conventionalfixedmortgage',
       'Sub_product_Othermortgage', 'Sub_product_not_available',
       'Issue_Loanservicingpaymentsescrowaccount',
       'Issue_Incorrectinformationoncreditreport',
       'Issue_Loanmodificationcollectionforeclosure', 'Company_Equifax',
       'Company_JPMorganChase&Co.', 'Company_WellsFargo&Company',
       'Company_BankofAmerica', 'State_TX', 'State_FL', 'State_CA',
       'Submittedvia_Phone', 'Submittedvia_Referral', 'Submittedvia_Web',
       'Companyresponsetoconsumer_Closedwithnon_monetaryrelief',
       'Companyresponsetoconsumer_Closedwithexplanation',
       'TimelyresponseQ_Yes'],
      dtype='object')

In [104]:
grid_search.fit(x_train1 , y_train1)

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: Future

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserW

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: Future

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserW

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: Future

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserW

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.]),
                         'class_weight': ['balanced'], 'n_jobs': [-1],
                         'penalty': ['l1', 'l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc

In [105]:
logr = grid_search.best_estimator_

In [106]:
logr.fit(x_train1 , y_train1)

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=-1, penalty='l1',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [107]:
train1_score = logr.predict_proba(x_train1)[:,1]

In [108]:
train1_score

array([0.35451631, 0.44071972, 0.51603265, ..., 0.49569561, 0.45192418,
       0.4923338 ])

In [111]:
train1_score.shape

(358815,)

In [109]:
train2_score = logr.predict_proba(x_train2)[:,1]

In [110]:
train2_score

array([0.40270356, 0.47253841, 0.52274161, ..., 0.44991992, 0.58974324,
       0.61936143])

In [112]:
train2_score.shape

(119606,)

In [113]:
train1_classes = (train1_score>0.5).astype(int)

In [114]:
train1_classes

array([0, 0, 1, ..., 0, 0, 0])

In [173]:
train1_classes.shape

(358815,)

In [115]:
y_train1_classes = np.where(y_train1=="Yes",1,0)

In [116]:
y_train1_classes

array([0, 0, 0, ..., 0, 0, 0])

In [117]:
train1_score[train1_score>0.5].size*100/train1_score.size

51.41340244973036

In [118]:
train2_classes=(train2_score>0.5).astype(int)

In [119]:
train2_classes

array([0, 0, 1, ..., 0, 1, 1])

In [175]:
train2_classes.shape

(119606,)

In [120]:
y_train2_classes = np.where(y_train2=="Yes",1,0)

In [121]:
y_train2_classes

array([0, 1, 0, ..., 0, 0, 0])

In [122]:
train2_score[train2_score>0.5].size*100/train2_score.size

51.373676905840846

In [123]:
roc_auc_score(y_train1, train1_classes) #auc score of train 1

0.5732954813701572

In [124]:
roc_auc_score(y_train2, train2_classes) 

0.5704647467325201

In [145]:
roc_auc_score(y_train2 , train2_classes)

0.5704647467325201

In [125]:
y_train1_classes.shape

(358815,)

In [126]:
y_train2_classes.shape

(119606,)

In [146]:
pd.DataFrame(y_train2_classes).to_csv("Nitesh_Bhosle_cc_test_hard_values.csv",index=False)

In [147]:
pd.DataFrame(y_train1_classes).to_csv("Nitesh_Bhosle_cc_358815_value.csv",index=False)

In [176]:
pd.DataFrame(train1_classes).to_csv("train1_classes_358815_hard_values.csv",index=False)

In [177]:
pd.DataFrame(train2_classes).to_csv("train2_classes_119606_hard_values.csv",index=False)

## another method

In [127]:
clf = RandomForestClassifier(verbose=True,n_jobs=-1)

In [136]:
param_dist = {"n_estimators":[100,200,300,500,700,1000],
              "max_features": [5,10,15,20,25],
              "bootstrap": [True, False],
              'class_weight':['balanced'], 
                'criterion':['entropy','gini'],
                'max_depth':[None,5,10,15,20,30,50,70],
                'min_samples_leaf':[1,2,5,10,15,20], 
                'min_samples_split':[2,5,10,15,20]
                  }

In [137]:
# run randomized search
n_iter_search = 3

In [ ]:
# n_iter parameter of RandomizedSeacrhCV controls, how many 
# parameter combination will be tried; out of all possible given values

In [138]:
 
random_search = RandomizedSearchCV(clf, param_distributions=param_dist,
                                   n_iter=n_iter_search,scoring='roc_auc',cv=3)

In [139]:
random_search.fit(x_train1 , y_train1)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   18.1s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  1.8min finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    2.2s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:    3.6s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   15.4s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  1.7min finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.5s
[Parallel(n_jobs=4)]: Done 192 tasks      | e

RandomizedSearchCV(cv=3, error_score='raise-deprecating',
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    n_estimators='warn',
                                                    n_jobs=-1, 

In [140]:
random_search.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=70, max_features=20,
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=5,
                       min_samples_split=20, min_weight_fraction_leaf=0.0,
                       n_estimators=300, n_jobs=-1, oob_score=False,
                       random_state=None, verbose=True, warm_start=False)

In [141]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.5f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [142]:
report(random_search.cv_results_,5)

Model with rank: 1
Mean validation score: 0.595 (std: 0.00122)
Parameters: {'n_estimators': 300, 'min_samples_split': 20, 'min_samples_leaf': 5, 'max_features': 20, 'max_depth': 70, 'criterion': 'gini', 'class_weight': 'balanced', 'bootstrap': True}

Model with rank: 2
Mean validation score: 0.593 (std: 0.00122)
Parameters: {'n_estimators': 1000, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 20, 'max_depth': None, 'criterion': 'gini', 'class_weight': 'balanced', 'bootstrap': True}

Model with rank: 3
Mean validation score: 0.587 (std: 0.00120)
Parameters: {'n_estimators': 300, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 20, 'max_depth': 30, 'criterion': 'gini', 'class_weight': 'balanced', 'bootstrap': True}



In [143]:
rf = RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=70, max_features=20,
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=5,
                       min_samples_split=20, min_weight_fraction_leaf=0.0,
                       n_estimators=300, n_jobs=-1, oob_score=False,
                       random_state=None, verbose=True, warm_start=False)


In [144]:
rf.fit(x_train1 , y_train1)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   27.0s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  3.1min finished


RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=70, max_features=20,
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=5,
                       min_samples_split=20, min_weight_fraction_leaf=0.0,
                       n_estimators=300, n_jobs=-1, oob_score=False,
                       random_state=None, verbose=True, warm_start=False)

In [148]:
train11_score = rf.predict_proba(x_train1)[:,1]

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    1.6s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    6.9s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:   11.0s finished


In [149]:
train11_score

array([0.1089358 , 0.50294929, 0.37175711, ..., 0.4584132 , 0.4804769 ,
       0.48994014])

In [165]:
train11_score.shape

(358815,)

In [150]:
train22_score = rf.predict_proba(x_train2)[:,1]

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    2.5s
[Parallel(n_jobs=4)]: Done 300 out of 300 | elapsed:    4.0s finished


In [151]:
train22_score

array([0.15168242, 0.35136398, 0.52858264, ..., 0.40185318, 0.65516877,
       0.68352552])

In [166]:
train22_score.shape

(119606,)

In [153]:
train11_classes = (train11_score>0.5).astype(int)

In [154]:
train11_classes

array([0, 1, 0, ..., 0, 0, 0])

In [167]:
train11_classes.shape

(358815,)

In [155]:
y_train11_classes = np.where(y_train1=="Yes",1,0)

In [156]:
y_train11_classes

array([0, 0, 0, ..., 0, 0, 0])

In [168]:
y_train11_classes.shape

(358815,)

In [157]:
train11_score[train11_score>0.5].size*100/train11_score.size #percent of Yes in train 1

51.80580521996015

In [158]:
train22_classes = (train22_score>0.5).astype(int)

In [159]:
train22_classes

array([0, 0, 1, ..., 0, 1, 1])

In [169]:
train22_classes.shape

(119606,)

In [160]:
y_train22_classes = np.where(y_train2=="Yes",1,0)

In [161]:
y_train22_classes

array([0, 1, 0, ..., 0, 0, 0])

In [170]:
y_train22_classes.shape

(119606,)

In [162]:
train22_score[train22_score>0.5].size*100/train22_score.size #percent of Yes in train 2

51.84188084209822

In [163]:
roc_auc_score(y_train1, train11_classes)

0.6119824635090481

In [164]:
roc_auc_score(y_train2, train22_classes)

0.5687818104600229

In [171]:
pd.DataFrame(y_train22_classes).to_csv("cc_test_randomforest_hardvalues_values.csv",index=True)

In [172]:
pd.DataFrame(y_train11_classes).to_csv("cc_358815_randomforest_hardvalues_values.csv",index=True)

In [178]:
pd.DataFrame(train11_classes).to_csv("train11_classes_358815_hard_values.csv",index=False)

In [179]:
pd.DataFrame(train22_classes).to_csv("train22_classes_119606_hard_values.csv",index=False)